imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.product_images: /uploads/images/produits

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
        
    translator: { fallbacks: [ "en" ] }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    
easy_admin:
    site_name: 'Administration Boutique'
    entities:
        Categorie:
            class: AppBundle\Entity\Categorie
            permissions:
                list:  ['ROLE_ADMIN']
                create:  ['ROLE_ADMIN']
                edit:  ['ROLE_ADMIN']
                delete:  ['ROLE_ADMIN']
            label: 'Categorie'
            list:
                title: 'Liste de catégories'
                actions: 
                    - { name: 'show', icon: 'search', label: '', title: 'Voir' }
                    - { name: 'edit', icon: 'pencil', label: '', title: 'Editer' }
                    - { name: 'delete', icon: 'remove', label: '', title: 'Supprimer' }
            edit:
                title: 'Detail catégorie (#%%entity_id%%)'
            new:
                title: 'Nouvelle catégorie'            
                
        Article:
            class: AppBundle\Entity\Article
            permissions:
                list:  ['ROLE_ADMIN']
                create:  ['ROLE_ADMIN']
                edit:  ['ROLE_SUPER']
                delete:  ['ROLE_SUPER']
            form:
                fields:
                    - 'designation'
                    - 'description'
                    - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.product_images%' }
                    - { property: 'categorie', type:'entity', type_options:{class:'AppBundle:Categorie',choice_label:'nom'}}
                    # - { property: 'vendeurs', type:'AppBundle\Form\ArticleVendeurType',label:'Article information'}
                    # - { property: 'vendeurs', type:'collection', type_options:{entry_type:'AppBundle\Form\ArticleVendeurType',label:false}}
            new:
                title: 'Nouvelle Article'
            list:
                actions: 
                    - { name: 'show', icon: 'search', label: '', title: 'Voir' }
                    - { name: 'edit', icon: 'pencil', label: '', title: 'Editer' }
                    - { name: 'delete', icon: 'remove', label: '', title: 'Editer' }
                    
                fields:
                    - 'id'
                    - 'designation'
                    - { property: 'imageurl', type: 'image', base_path: '%app.path.product_images%' }
                    - 'categorie.nom'
            show:
                fields:
                    - 'designation'
                    - 'description'
                    - { property: 'imageurl', type: 'image', base_path: '%app.path.product_images%' }
                    - 'categorie.nom'
        
        Article_du_vendeur:
            class: AppBundle\Entity\Articlevendeur
            permissions:
                list:  ['ROLE_ADMIN']
                create:  ['ROLE_ADMIN']
                edit:  ['ROLE_SUPER']
                delete:  ['ROLE_SUPER']         
            form:
                fields:
                    - { property: 'article', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Article' } }
                    - 'quantite'
                    - 'payablenfois'
                    - 'prix'   

            list:
                actions: 
                    - { name: 'show', icon: 'search', label: '', title: 'Voir' }
                    - { name: 'edit', icon: 'pencil', label: '', title: 'Editer' }
                    - { name: 'delete', icon: 'remove', label: '', title: 'Editer' }  

        User:
            class: AppBundle\Entity\User
            permissions:
                list:  ['ROLE_SUPER']
                create:  ['ROLE_SUPER']
                edit:  ['ROLE_SUPER']
                delete:  ['ROLE_SUPER']
            form:
                fields:
                    - 'email' 
                    - 'nom'
                    - { property: 'enabled', type: 'checkbox' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'CLIENT': 'ROLE_CLIENT', 'VENDEUR': 'ROLE_VENDEUR', 'ADMINISTRATEUR':'ROLE_ADMINISTRATEUR' } } }
            list:
                fields:
                    - 'Email'
                    - { property: 'Enabled', type: 'toggle' }
                    - { property: 'Last login', type: 'datetime' }
                    - 'Roles'

        Client:
            class: AppBundle\Entity\Client
            permissions:
                list:  ['ROLE_SUPER']
                create:  ['ROLE_SUPER']
                edit:  ['ROLE_SUPER']
                delete:  ['ROLE_SUPER']
            form:
                fields:
                    - 'nom' 
                    - 'prenom'
                    - 'email'
                    - 'adresse'
                    - 'telephone'
                    - 'googleidentifier'
                    - { property: 'vendeur', type:'entity', type_options:{class:'AppBundle:Vendeur',choice_label:'nomVendeur'}}
                    - { property: 'user', type:'entity', type_options:{class:'AppBundle:User',choice_label:'email'}}
        Vendeur:
            class: AppBundle\Entity\Vendeur
            permissions:
                list:  ['ROLE_SUPER']
                create:  ['ROLE_SUPER']
                edit:  ['ROLE_SUPER']
                delete:  ['ROLE_SUPER']
            form:
                fields:
                    - 'nomVendeur'
                    - 'adresseVendeur'
            list:
                fields:
                    - 'id'
                    - 'nomVendeur'
                    - 'adresseVendeur'
        Commentaire:
            class: AppBundle\Entity\Vendeur
            permissions:
                list:  ['ROLE_SUPER']
                create:  ['ROLE_SUPER']
                edit:  ['ROLE_SUPER']
                delete:  ['ROLE_SUPER']

    design:
        brand_color: '#9c1b54'
        assets:
            #favicon: ''
            
vich_uploader:
    db_driver: orm
    mappings:
        images_produits:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/produits'

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "mymarketboutique@gmail.com"
        sender_name: "mymarketboutique"
    registration:
        form:
            type: AppBundle\Form\RegistrationType
